apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        imagePullPolicy: Always
        args:
        - "--keygen-enable"
      restartPolicy: OnFailure
