apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: "gcr.io/kuar-demo/kuard-amd64:green"
          


